const members = [
  {
    first: 'Nathan',
    last: 'Tahbaz',
    role: 'CEO',
    photo: require('../../images/team/real/nathan.png'),
    cartoon: require('../../images/team/cartoons/nathan.png'),
    description: `Nathan is a space nerd with experience in management, systems, rapid prototyping, manufacturing, and project management. He has a Bachelor's degree in Mechanical Engineering and a Master's degree in Space Systems Engineering from Stevens Institute of Technology.`,
    linkedin: 'nathan-tahbaz',
  },
  {
    first: 'Monica',
    last: 'Traupmann',
    role: 'COO',
    photo: require('../../images/team/real/monica.png'),
    cartoon: require('../../images/team/cartoons/monica.png'),
    linkedin: 'monica-traupmann',
    description:
      'Monica is an explosions enthusiast with experience in propulsion design, fuel delivery systems, and instrumentation, as well as fundraising and crowdfunding for small-scale projects. She has a Bachelor’s degree in Chemical Engineering and a Master’s degree in Mechanical Engineering with a focus on Energy, Fluids, and Heat Transfer.',
  },
  {
    first: 'Benjamin',
    last: 'Iofel',
    role: 'CIO',
    photo: require('../../images/team/real/ben.png'),
    cartoon: require('../../images/team/cartoons/ben.png'),
    linkedin: 'beniofel',
    github: 'benwaffle',
    description: `Ben is a computer expert with extensive experience in software development, embedded programming, and Linux. He is a software engineer at Flow and brings that culture and experience to Hudson Space Systems. He has a B.S. in Computer Science.`,
  },
  {
    first: 'William',
    last: 'Skwirut',
    role: 'CTO',
    photo: require('../../images/team/real/will.png'),
    cartoon: require('../../images/team/cartoons/will.png'),
    linkedin: 'williamskwirut',
    description: `Will’s background includes designing, manufacturing, and testing fluid control components and systems. He also has experience in numerical analysis, rapid prototyping, computational fluid dynamics, and finite element analysis. Will has Bachelor’s and Master’s Degrees in Mechanical Engineering from Stevens Institute of Technology, specializing in Fluids, Thermal, and Energy.`,
  },
  {
    first: 'Dakota',
    last: 'Van Deursen',
    role: 'CFO',
    photo: require('../../images/team/real/dakota.png'),
    cartoon: require('../../images/team/cartoons/dakota.png'),
    linkedin: 'dvandeursen',
    description: `Dakota is passionate about learning how complex systems work together - both physically and socially. He weaves experience with STEM in the workplace into his personal history in peer management and governing bodies. He has a B.Eng. in Chemical Engineering and an M.S. in Materials Science & Engineering from Stevens Institute of Technology.`,
  },
  {
    first: 'Nicholas',
    last: 'Yarbrough',
    role: 'Engineer',
    photo: require('../../images/team/real/cole.png'),
    cartoon: require('../../images/team/cartoons/cole.png'),
    linkedin: 'cole-yarbrough-2a39551b2',
    description: `Cole is a lifelong maker and electrical / computer engineer who has worked on space projects both small and large: from communicating with the ISS to launching a high-altitude balloon. Cole leads the development of avionics hardware for our suborbital launch platforms.`,
  },
  {
    first: 'Igor',
    last: 'Alexandrov',
    role: 'Senior Advisor',
    photo: require('../../images/team/real/igor.png'),
    cartoon: require('../../images/team/cartoons/igor.png'),
    linkedin: 'igor-alexandrov-033123',
    description:
      'Igor is an experienced president with a demonstrated history of working in the research industry. Strong business development professional skilled in Analytical Skills, Entrepreneurship, Fundraising, Software Development, and Start-ups.',
  },
  {
    first: 'Khurram',
    last: 'Nasir Gore',
    role: 'Senior Advisor',
    photo: require('../../images/team/real/khurram.png'),
    cartoon: require('../../images/team/cartoons/khurram.png'),
    linkedin: 'kngore',
    description:
      'Khurram is a business executive, attorney, engineer and an advocate for diversity and STEM.  With over 20 years in the tech and innovation space, his work brings together a deep understanding of business development, product lifecycle, data ethics, and the legal implications and challenges for companies that push boundaries.',
  },
]

export default members
